### PR TITLE
0.0.0c_SW-update

### PR DESCRIPTION
**Pull request by jackstonebridge**
Why don't we merge the ServiceWorker updates into the re-rooting process?

### CODE REVIEW

**Comment by jackstonebridge** [comment]
@andrealeone perfect. Which to prioritize?

**Comment by andrealeone** [comment]
[_Re-root](https://github.com/LionAndTheFellows/TelegramClient/tree/_Re-root), definitely. The ServiceWorker can wait for now.

**Comment by andrealeone** [comment]
WTF?!

**Comment by jackstonebridge** [comment]
My mistake. Sorry...

**Pull request merged**
